[default]
workshop = [
    "450814997", # CBA_A3's Workshop ID
    "463939057", # ACE3's Workshop ID
    # "2774641073", # KAT - Advanced Medical DEV's Workshop ID
    "2020940806", # KAM Advanced Pharma's Workshop ID
]
